debug: true

collections:
    live: $live

    combined:
        sequence:
            - name: store_filter
              index:
                type: file_filter
                path: ./collections/store/indexes/autoindex.cdxj

              archive_paths: ./collections/store/archive/

            - name: scalar
              index: live_filter

            - name: store
              index: ./collections/store/indexes/
              archive_paths: ./collections/store/archive/

    all:
        sequence:
            - name: store_filter
              index:
                type: file_filter
                path: ./collections/store/indexes/autoindex.cdxj

              archive_paths: ./collections/store/archive/

            - name: scalar
              index: live_filter

            - name: store
              index: ./collections/store/indexes/
              archive_paths: ./collections/store/archive/

    patch:
        sequence:
            - name: scalar
              index: live_filter

            - name: store
              index: ./collections/store/indexes/
              archive_paths: ./collections/store/archive/

            - name: live
              index: $live

recorder: live

autoindex: 30

proxy:
    coll: live
    use_banner: false

